language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: andrewcstewart
  password:
    secure: lhSBH6g3XgyblKvNTQzAXe7jgPXsFjgQjP5/VRiclbAPywpOsugaMSSGfLKpIAwxoNU5TCanLfkvEkyhFcd8Md9Aq/VHYhaSXv64HdacGx1Jj8sSS+L5akRs8I23w4ef4irfv6yY4nCghtbcbvzkVXGY/EyiXkWQpP2xmI78BDQCVbxFXWaxX7Vo4MASliLMv3Da2R+XJYojis2O9Hp8IWyQfRMpUq/TV7ENQoJvVv+O1lsE2VuJhZKAvUgR0opfwFHwnTzVcl7OGTOmCJ6lWd10q0Gy3Q9T0qRtSJvMSmW2AoU/pQrfqzPMzSKfHk2l66Roxn9bQKTQ0j2xXBRwxRVU3y+FHTZkuH+Dzxa3BjBMfwxdtqUYP6mElrODA0xAq5eoSQ+Xs+uGZC9mw4qbLcYwqCWz8whbLMLMFemj9cAP+chjvsW0zFiIx6Sdas1o6cIhsDO2JcNUKQVgOT+K7NSP32FlZUStf0JDalRYZ+ASDAw21B0qi0AmV+RXVhCrFy+R837avROVY7Od/9wQnCCr8S1TR9DRf3gNPhiw/OTGUFgIKyCr+/8BSISR9JxUoS4uU7hP+nWvOp3h1OMLaTNDm1ctgql3GZSzVTUIaqI2ZY0oKshL3SwOvl5oTsiZcI+7OQKlGM5kVIy5SwKAu4MTfH62vEGrEtMmINMrxjk=
  on:
    tags: true
    repo: fundamentals-of-data-science/ds-fundamentals-python
    python: 3.6
