language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: andrewcstewart
  password:
    secure: lhSBH6g3XgyblKvNTQzAXe7jgPXsFjgQjP5/VRiclbAPywpOsugaMSSGfLKpIAwxoNU5TCanLfkvEkyhFcd8Md9Aq/VHYhaSXv64HdacGx1Jj8sSS+L5akRs8I23w4ef4irfv6yY4nCghtbcbvzkVXGY/EyiXkWQpP2xmI78BDQCVbxFXWaxX7Vo4MASliLMv3Da2R+XJYojis2O9Hp8IWyQfRMpUq/TV7ENQoJvVv+O1lsE2VuJhZKAvUgR0opfwFHwnTzVcl7OGTOmCJ6lWd10q0Gy3Q9T0qRtSJvMSmW2AoU/pQrfqzPMzSKfHk2l66Roxn9bQKTQ0j2xXBRwxRVU3y+FHTZkuH+Dzxa3BjBMfwxdtqUYP6mElrODA0xAq5eoSQ+Xs+uGZC9mw4qbLcYwqCWz8whbLMLMFemj9cAP+chjvsW0zFiIx6Sdas1o6cIhsDO2JcNUKQVgOT+K7NSP32FlZUStf0JDalRYZ+ASDAw21B0qi0AmV+RXVhCrFy+R837avROVY7Od/9wQnCCr8S1TR9DRf3gNPhiw/OTGUFgIKyCr+/8BSISR9JxUoS4uU7hP+nWvOp3h1OMLaTNDm1ctgql3GZSzVTUIaqI2ZY0oKshL3SwOvl5oTsiZcI+7OQKlGM5kVIy5SwKAu4MTfH62vEGrEtMmINMrxjk=
  on:
    tags: true
    repo: fundamentals-of-data-science/ds-fundamentals-python
    python: 3.6
notifications:
  slack:
    secure: tCijmSLRg6+wmntbG6sxDCAoO3Ck2+7sejhIx0LYNoFMALLWCZAHy5EAEvr6lzIFTMt77t5AzvWkiaw0mghTthFH4wwkN+Q30mwFG3nlJTEgHiWQs/9LRx7a8cdEE1f+OioMME+mNUCedxqCfP5/m3L8OfN+T2bWsY2xUYaF/loC/ubQi9fcGXyuwfnkbs5MJzs5qTcWYpUmXRxzlLOQReme5/a9mbDsQGfm5PFJEh0qV+/rvXW9l7vNnUDJTwbK5rnON66jnv6HlTqk1dOdISPwZHA195RNpkwJxoJcjvIDVwPZzOwdStW9Rt1MUax5HqHHozriecpTbx7VP3ztQkPHfdGAhq2sCxKzWw07UJjB7HHmBVnL4XqhKbd/EzNOSAZ4CrjfAzRINkJWgT6FsN21Dun0FLIMRiFQcGOpHY8yNCCafNEby717nzRzNAEZLt/EOPYLlaK0DC0znCSwJRlLZ4ffuiqOMQIy0q2NcIkc5JIFZRZPLNueCbluNjwB5fHLHjsTaQAw+5Jy1kDgbB9k0EjfPZpbTcXO+uTwAaGVxf0tbU8PIE0MJ7VemK8Q2q2QSuOOx0QAA3G444EnC7kDhXbU4xcynp/Ov17TGdXUcc7orqA7895YQfc5nu7kpEX64da7G0Jia0X3z2P+ahqezDZV3f22l3xrqWOo4uE=
